main/urls.py
from django.urls import path
from main.views import show_main, create_shop_entry, show_xml, show_json, show_xml_by_id, show_json_by_id
from main.views import register, login_user, logout_user
from main.views import edit_shop_item, delete_shop_item
from main.views import add_shop_entry_ajax

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    
    path('create-shop-entry', create_shop_entry, name='create_shop_entry'),
    
    path('xml/', show_xml, name='show_xml'),

    path('json/', show_json, name='show_json'),

    path('xml/<str:id>/', show_xml_by_id, name='show_xml_by_id'),
    
    path('json/<str:id>/', show_json_by_id, name='show_json_by_id'),
    
    path('register', register, name='register'),
    
    path('login', login_user, name='login'),
    
    path('logout', logout_user, name='logout'),
    
    path('edit-shop-item/<uuid:id>', edit_shop_item, name='edit_shop_item'),
    
    path('delete-shop-item/<uuid:id>', delete_shop_item, name='delete_shop_item'),
    
    path('add-shop-entry-ajax', add_shop_entry_ajax, name='add_shop_entry_ajax'),    
]

pbp_store/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

pbp_tugas2/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
     path('', include('main.urls')),
]

main/models.py
import uuid  # tambahkan baris ini di paling atas
from django.db import models

from django.contrib.auth.models import User


# Create your models here.
class ShopEntry(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    # on delete = kalo delet user, 
    # semua shopentry si user ke delete
    
    # id
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)  # tambahkan baris ini

    # wajib
    name = models.CharField(max_length=255)
    price = models.IntegerField()
    description = models.TextField()
    
    # optional
    sold = models.IntegerField(default=0)
    rating = models.FloatField(default=None)
    
    @property
    def is_top_seller(self):
        return self.sold > 1000 and self.rating > 4.0
    
# cara bikin many ot many
# class EmployeeEntry(models.Model):
#     department = models.ManyToManyField(models.DepartmentEntry)
#     name = models.CharField(max_length=255)    
#     # id
#     id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)  # tambahkan baris ini
    
# class DepartmentEntry(models.Model):
#     id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)  # tambahkan baris ini
#     name = models.CharField(max_length=255)

main/forms.py
from django.forms import ModelForm
from main.models import ShopEntry
from django.utils.html import strip_tags

class ShopEntryForm(ModelForm):
    class Meta:
        model = ShopEntry
        fields = ["name", "price", "description", "sold", "rating"]
        
        def clean_name(self):
            name = self.cleaned_data["name"]
            return strip_tags(name)
        
        def clean_price(self):
            price = self.cleaned_data["price"]
            return strip_tags(price)
        def clean_description(self):
            description = self.cleaned_data["description"]
            return strip_tags(description)
        def clean_sold(self):
            sold = self.cleaned_data["sold"]
            return strip_tags(sold)
        def clean_rating(self):
            rating = self.cleaned_data["rating"]
            return strip_tags(rating)

main/views.py
from django.shortcuts import render, redirect, reverse   # Tambahkan import redirect di baris ini
from main.forms import ShopEntryForm
from main.models import ShopEntry
from django.http import HttpResponse
from django.core import serializers

from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse

from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.utils.html import strip_tags

import json
from django.http import JsonResponse



# Create your views here.
@login_required(login_url='/login')
def show_main(request):
    context = {
        'npm' : '2306220444',
        'name': request.user.username,
        'class': 'PBP D',
        'last_login': request.COOKIES['last_login'],
    }

    return render(request, "main.html", context)

def create_shop_entry(request):
    form = ShopEntryForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        shop_entry = form.save(commit=False)
        shop_entry.user = request.user
        shop_entry.save()
        return redirect('main:show_main')

    context = {'form': form}
    return render(request, "create_shop_entry.html", context)

def show_xml(request):
    data = ShopEntry.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = ShopEntry.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = ShopEntry.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = ShopEntry.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data),content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
   if request.method == 'POST':
    form = AuthenticationForm(data=request.POST)
    
    if form.is_valid():
        user = form.get_user()
        login(request, user)
        response = HttpResponseRedirect(reverse("main:show_main"))
        response.set_cookie('last_login', str(datetime.datetime.now()))
        return response
    else:
        messages.error(request, "Invalid username or password. Please try again.")

   else:
      form = AuthenticationForm(request)
   context = {'form': form}
   return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def edit_shop_item(request, id):
    # Get shop entry berdasarkan id
    shop_item = ShopEntry.objects.get(pk = id)

    # Set shop entry sebagai instance dari form
    form = ShopEntryForm(request.POST or None, instance=shop_item)

    if form.is_valid() and request.method == "POST":
        # Simpan form dan kembali ke halaman awal
        form.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "edit_shop_item.html", context)

def delete_shop_item(request, id):
    # Get shop berdasarkan id
    item = ShopEntry.objects.get(pk = id)
    # Hapus shop
    item.delete()
    # Kembali ke halaman awal
    return HttpResponseRedirect(reverse('main:show_main'))

@csrf_exempt
@require_POST
def add_shop_entry_ajax(request):
    name = strip_tags(request.POST.get("name"))
    price = strip_tags(request.POST.get("price"))
    description = strip_tags(request.POST.get("description"))
    sold = strip_tags(request.POST.get("sold"))
    rating = strip_tags(request.POST.get("rating"))
    user = request.user

    new_shop_entry = ShopEntry(
        name=name, price=price, description=description, sold=sold, rating=rating,
        user=user
    )
    new_shop_entry.save()

    return HttpResponse(b"CREATED", status=201)

main/templates/card_info.html
<div class="bg-muted rounded-xl overflow-hidden border-2 border-highlight">
    <div class="p-4">
      <h5 class="text-lg font-semibold text-primary">{{ title }}</h5>
      <p class="text-primary">{{ value }}</p>
    </div>
</div>

main/templates/card_shop_item.html
<div class="relative ">
  <div class="absolute top-2 z-10 left-1/2 -translate-x-1/2 flex items-center -space-x-2 h-fit">
  </div>
  <div class="relative top-5 bg-yellow-100/20 shadow-md rounded-lg mb-6 break-inside-avoid flex flex-col border-2 border-yellow-700 transform transition-transform duration-300 h-fit  ">
    <div class="flex bg-[#f9e4bc] rounded-t-lg w-full justify-between">
      <div class="text-gray-800 p-4 rounded-tl-lg w-[80%]">
        <h1 class="font-bold text-5xl mb-2 overflow-clip ">{{shop_entry.name}}</h1>
        <p class="text-gray-800">Rp{{shop_entry.price}}</p>
      </div>
      <div class="flex flex-col flex h-full w-fit">
        <a href="{% url 'main:edit_shop_item' shop_entry.pk %}" class="bg-yellow-600 hover:bg-yellow-800 text-white p-2 transition duration-300 shadow-md rounded-tr-md">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-full w-7" viewBox="0 0 20 20" fill="currentColor">
            <path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z" />
          </svg>
        </a>
        <a href="{% url 'main:delete_shop_item' shop_entry.pk %}" class="bg-red-600 hover:bg-red-800 text-white p-2 transition duration-300 shadow-md rounded-bl-lg">
          <svg xmlns="http://www.w3.org/2000/svg" class="w-7" viewBox="0 0 20 20" fill="currentColor">
            <path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd" />
          </svg>
        </a>
      </div>
    </div>
    <div class="p-4">
      <p class="font-semibold text-lg mb-2">Info:</p> 
      <p class="text-gray-700 mb-2">
        <span >Rating: {{shop_entry.rating}}</span>
      </p>
      <p class="text-gray-700 mb-2">
        <span >Terjual: {{shop_entry.sold}}</span>
      </p>

      <div class="mt-4 w-full">
        <p class="text-gray-700 font-semibold mb-2">Deskripsi</p>
        <p class="text-gray-700 font-semibold mb-2">{{shop_entry.description}}</p>
        
        {% comment %} <div class="relative pt-1">
        </div> {% endcomment %}
      </div>
    </div>
  </div>
  
</div>

main/templates/create_shop_entry.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<title>Add new Shop Entry</title>
{% endblock meta %}

{% block content %}
{% include 'navbar.html' %}

<div class="flex flex-col min-h-screen bg-primary">
  <div class="container mx-auto px-4 py-8 mt-16 max-w-xl">
    <h1 class="text-3xl font-bold text-center mb-8 text-black">Create New Shop Entry</h1>
  
    <div class="bg-white shadow-md rounded-lg p-6 form-style">
      <form method="POST" class="space-y-6">
        {% csrf_token %}
        {% for field in form %}
          <div class="flex flex-col">
            <label for="{{ field.id_for_label }}" class="mb-2 font-semibold text-gray-700">
              {{ field.label }}
            </label>
            <div class="w-full">
              {{ field }}
            </div>
            {% if field.help_text %}
              <p class="mt-1 text-sm text-gray-500">{{ field.help_text }}</p>
            {% endif %}
            {% for error in field.errors %}
              <p class="mt-1 text-sm text-red-600">{{ error }}</p>
            {% endfor %}
          </div>
        {% endfor %}
        <div class="flex justify-center mt-6">
          <button type="submit" class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-secondary hover:opacity-90">
            Create Shop Entry
          </button>
        </div>
      </form>
    </div>
  </div>
</div>

{% endblock %}

main/templates/main.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Mental Health Tracker</title>
<script src="https://cdn.jsdelivr.net/npm/dompurify@3.1.7/dist/purify.min.js"></script>

{% endblock meta %}

{% block content %}
{% include 'navbar.html' %}
<div class="overflow-x-hidden px-4 md:px-8 pb-8 pt-24 min-h-screen bg-primary flex flex-col">
  <div class="p-2 mb-6 relative">
    <div class="relative grid grid-cols-1 z-30 md:grid-cols-3 gap-8">
      {% include "card_info.html" with title='NPM' value=npm %}
      {% include "card_info.html" with title='Name' value=name %}
      {% include "card_info.html" with title='Class' value=class %}
    </div>
    <div class="w-full px-6  absolute top-[44px] left-0 z-20 hidden md:flex">
      <div class="w-full min-h-4 bg-secondary">
      </div>
    </div>
    <div class="h-full w-full py-6  absolute top-0 left-0 z-20 md:hidden flex ">
      <div class="h-full min-w-4 bg-secondary mx-auto">
      </div>
    </div>
</div>
    <div class="px-3 mb-4">
      <div class="flex rounded-md items-center bg-highlight py-2 px-4 w-fit">
        <span class="text-black font-medium text-center">Last Login: {{last_login}}</span>
      </div>
    </div>
    <div class="flex justify-end mb-6 gap-4">
        <a href="{% url 'main:create_shop_entry' %}" class="bg-secondary text-white font-bold py-2 px-4 rounded-lg transition duration-300 ease-in-out transform hover:-translate-y-1 hover:scale-105">
            Add New Shop Item
        </a>
        <button data-modal-target="crudModal" data-modal-toggle="crudModal" class="btn bg-highlight hover:bg-highlight text-white font-bold py-2 px-4 rounded-lg transition duration-300 ease-in-out transform hover:-translate-y-1 hover:scale-105" onclick="showModal();">
          Add New Shop Entry by AJAX
        </button>
    </div>
    
    {% comment %} {% if not shop_entries %}
      <div class="flex flex-col items-center justify-center min-h-[24rem] p-6">
        <p class="text-center text-gray-600 mt-4">Belum ada item dalam PBP Shop :|.</p>
      </div>
    {% else %}
      <div class="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-3 gap-10">
        {% for shop_entry in shop_entries %}
            {% include 'card_shop_item.html' with shop_entry=shop_entry%}
        {% endfor %}
      </div>
    {% endif %} {% endcomment %}
    <div id="shop_entry_cards"></div>

    <div id="crudModal" tabindex="-1" aria-hidden="true" class="hidden fixed inset-0 z-50 w-full flex items-center justify-center bg-primary bg-opacity-50 overflow-x-hidden overflow-y-scroll transition-opacity duration-300 ease-out">
      <div id="crudModalContent" class="relative bg-white rounded-lg shadow-lg w-5/6 sm:w-3/4 md:w-1/2 lg:w-1/3 mx-4 sm:mx-0 transform opacity-0 transition-transform transition-opacity duration-300 ease-out h-fit pt-[120px]">
        <!-- Modal header -->
        <div class="flex items-center justify-between p-4 border-b rounded-t">
          <h3 class="text-xl font-semibold text-gray-900">
            Add New Shop Entry
          </h3>
          <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center" id="closeModalBtn">
            <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path>
            </svg>
            <span class="sr-only">Close modal</span>
          </button>
        </div>
        <!-- Modal body -->
        <div class="px-6 py-4 space-y-6 form-style">
          <form id="shopEntryForm">
            <div class="mb-4">
              <label for="name" class="block text-sm font-medium text-gray-700">name</label>
              <input type="text" id="name" name="name" class=" block w-full border border-gray-300 rounded-md p-2 hover:border-highlight" placeholder="Enter item name" required>
            </div>
            <div class="mb-4">
              <label for="price" class="block text-sm font-medium text-gray-700">price</label>
              <input type="number" id="price" name="price" class="mt-1 block w-full border border-gray-300 rounded-md p-2 hover:border-highlight" placeholder="Enter item price" required>
            </div>
            <div class="mb-4">
              <label for="description" class="block text-sm font-medium text-gray-700">Description</label>
              <textarea id="description" name="description" rows="3" class="mt-1 block w-full h-52 resize-none border border-gray-300 rounded-md p-2 hover:border-highlight" placeholder="Describe the item" required></textarea>
            </div>
            <div class="mb-4">
              <label for="sold" class="block text-sm font-medium text-gray-700">Sold</label>
              <input type="number" id="sold" name="sold" min="1" class="mt-1 block w-full border border-gray-300 rounded-md p-2 hover:border-highlight" required>
            </div>
            <div class="mb-4">
              <label for="rating" class="block text-sm font-medium text-gray-700">Rating</label>
              <input type="number" id="rating" name="rating" min="1" max="5" class="mt-1 block w-full border border-gray-300 rounded-md p-2 hover:border-highlight" required>
            </div>
          </form>
        </div>
        <!-- Modal footer -->
        <div class="flex flex-col space-y-2 md:flex-row md:space-y-0 md:space-x-2 p-6 border-t border-gray-200 rounded-b justify-center md:justify-end">
          <button type="button" class="bg-gray-500 hover:bg-gray-600 text-white font-bold py-2 px-4 rounded-lg" id="cancelButton">Cancel</button>
          <button type="submit" id="submitShopEntry" form="shopEntryForm" class="bg-secondary hover:bg-highlight text-white font-bold py-2 px-4 rounded-lg" disabled>Save</button>
        </div>
      </div>
    </div>
</div>

<script>
  function addShopEntry() {
    const form = document.querySelector('#shopEntryForm');
  
    fetch("{% url 'main:add_shop_entry_ajax' %}", {
      method: "POST",
      body: new FormData(form),
    })
    .then(response => {
      if (response.ok) {
        refreshShopEntries();
        form.reset();  // Reset form after successful submission
        hideModal();   // Close modal after submission
      }
    });

    return false;
  }

  async function getShopEntries(){
      return fetch("{% url 'main:show_json' %}").then((res) => res.json())
  }

  async function refreshShopEntries() {
    document.getElementById("shop_entry_cards").innerHTML = "";
    document.getElementById("shop_entry_cards").className = "";
    const shopEntries = await getShopEntries();
    let htmlString = "";
    let classNameString = "";

    if (shopEntries.length === 0) {
        classNameString = "grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 w-full";
        htmlString = `
             <div class="">
              <p class="text-center text-gray-600 mt-4">Belum ada item dalam PBP Shop :|.</p>
            </div>
        `;
    }
    else {
        classNameString = "grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 w-full"
        shopEntries.forEach((shop_entry) => {
            const name = DOMPurify.sanitize(shop_entry.fields.name);
            const price = DOMPurify.sanitize(shop_entry.fields.price);
            const description = DOMPurify.sanitize(shop_entry.fields.description);
            const rating = DOMPurify.sanitize(shop_entry.fields.rating);
            const sold = DOMPurify.sanitize(shop_entry.fields.sold);
            
            htmlString += `
            <div class="relative ">
              <div class="absolute top-2 z-10 left-1/2 -translate-x-1/2 flex items-center -space-x-2 h-fit ">
              </div>
              <div class="relative top-5 bg-yellow-100/20 shadow-md rounded-lg mb-6 break-inside-avoid flex flex-col border-2 border-yellow-700 transform transition-transform duration-300 h-fit  ">
                <div class="flex bg-[#f9e4bc] rounded-t-lg w-full justify-between">
                  <div class="text-gray-800 p-4 rounded-tl-lg w-[80%]">
                    <h1 class="font-bold text-5xl mb-2 overflow-clip ">${name}</h1>
                    <p class="text-gray-800">Rp${price}</p>
                  </div>
                  <div class="flex flex-col flex h-full w-fit">
                    <a href="edit-shop-item/${shop_entry.pk}" class="bg-yellow-600 hover:bg-yellow-800 text-white p-2 transition duration-300 shadow-md rounded-tr-md">
                      <svg xmlns="http://www.w3.org/2000/svg" class="h-full w-7" viewBox="0 0 20 20" fill="currentColor">
                        <path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z" />
                      </svg>
                    </a>
                    <a href="delete-shop-item/${shop_entry.pk}" class="bg-red-600 hover:bg-red-800 text-white p-2 transition duration-300 shadow-md rounded-bl-lg">
                      <svg xmlns="http://www.w3.org/2000/svg" class="w-7" viewBox="0 0 20 20" fill="currentColor">
                        <path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd" />
                      </svg>
                    </a>
                  </div>
                </div>
                <div class="p-4">
                  <p class="font-semibold text-lg mb-2">Info:</p> 
                  <p class="text-gray-700 mb-2">
                    <span >Rating: ${rating}</span>
                  </p>
                  <p class="text-gray-700 mb-2">
                    <span >Terjual: ${sold}</span>
                  </p>

                  <div class="mt-4 w-full">
                    <p class="text-gray-700 font-semibold mb-2">Deskripsi</p>
                    <p class="text-gray-700 font-semibold mb-2">${description}</p>
                    
                  </div>
                </div>
              </div>
              
            </div>
            `;
        });
    }
    document.getElementById("shop_entry_cards").className = classNameString;
    document.getElementById("shop_entry_cards").innerHTML = htmlString;
}
refreshShopEntries();

  function toggleSubmitButtonState() {
    const form = document.querySelector("#shopEntryForm");
    const submitButton = document.getElementById("submitShopEntry");

    // Enable the submit button only if all inputs are valid
    if (form.checkValidity()) {
      submitButton.disabled = false;
      submitButton.classList.remove("opacity-[0.3]");
      submitButton.classList.remove("cursor-not-allowed");
    } else {
      submitButton.disabled = true;
      submitButton.classList.add("opacity-[0.3]");
      submitButton.classList.add("cursor-not-allowed");
    }
  }

  const modal = document.getElementById('crudModal');
  const modalContent = document.getElementById('crudModalContent');

  function showModal() {
      const modal = document.getElementById('crudModal');
      const modalContent = document.getElementById('crudModalContent');

      modal.classList.remove('hidden'); 
      setTimeout(() => {
        modalContent.classList.remove('opacity-0', 'scale-95');
        modalContent.classList.add('opacity-100', 'scale-100');
      }, 50); 
  }

  function hideModal() {
      const modal = document.getElementById('crudModal');
      const modalContent = document.getElementById('crudModalContent');

      modalContent.classList.remove('opacity-100', 'scale-100');
      modalContent.classList.add('opacity-0', 'scale-95');

      setTimeout(() => {
        modal.classList.add('hidden');
      }, 150); 
  }

  document.getElementById("cancelButton").addEventListener("click", hideModal);
  document.getElementById("closeModalBtn").addEventListener("click", hideModal);

  document.getElementById("shopEntryForm").addEventListener("input", toggleSubmitButtonState);

  // Initially disable the submit button
  toggleSubmitButtonState();

  document.getElementById("submitShopEntry").onclick = addShopEntry

  
</script>

{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block meta %}
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1">
    {% endblock meta %}
    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@600&family=Source+Sans+Pro:wght@400&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/global.css' %}"/>

  </head>

  <body>
    {% block content %} {% endblock content %}
  </body>
</html>

templates/navbar.html
<nav class="bg-secondary shadow-lg fixed top-0 left-0 z-40 w-screen">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <div class="flex items-center justify-between h-16">
        <div class="flex items-center">
          <a href="/">
            <h1 class="text-2xl font-bold text-center text-white">PBP Shop</h1>
          </a>
        </div>
        <div class="hidden md:flex items-center">
          {% if user.is_authenticated %}
            <span class="text-gray-300 mr-4">Welcome, {{ user.username }}</span>
            <a href="{% url 'main:logout' %}" class="text-center bg-red-800 hover:bg-red-900 text-white font-bold py-2 px-4 rounded transition duration-300">
              Logout
            </a>
          {% else %}
            <a href="{% url 'main:login' %}" class="text-center bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded transition duration-300 mr-2">
              Login
            </a>
            <a href="{% url 'main:register' %}" class="text-center bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-4 rounded transition duration-300">
              Register
            </a>
          {% endif %}
        </div>
        <div class="md:hidden flex items-center">
          <button class="mobile-menu-button">
            <svg class="w-6 h-6 text-white" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor">
              <path d="M4 6h16M4 12h16M4 18h16"></path>
            </svg>
          </button>
        </div>
      </div>
    </div>
    <!-- Mobile menu -->
    <div class="mobile-menu hidden md:hidden  px-4 w-full md:max-w-full">
      <div class="pt-2 pb-3 space-y-1 mx-auto">
        {% if user.is_authenticated %}
          <span class="block text-gray-300 px-3 py-2">Welcome, {{ user.username }}</span>
          <a href="{% url 'main:logout' %}" class="block text-center bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 rounded transition duration-300">
            Logout
          </a>
        {% else %}
          <a href="{% url 'main:login' %}" class="block text-center bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded transition duration-300 mb-2">
            Login
          </a>
          <a href="{% url 'main:register' %}" class="block text-center bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-4 rounded transition duration-300">
            Register
          </a>
        {% endif %}
      </div>
    </div>
    <script>
      const btn = document.querySelector("button.mobile-menu-button");
      const menu = document.querySelector(".mobile-menu");
    
      btn.addEventListener("click", () => {
        menu.classList.toggle("hidden");
      });
    </script>
  </nav>